### ISSUE TITLE
Style Clinician Invite Form

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#233]
**Task:**

- [ ] Setup reusable components with styling on the Clinician Invite form:
    - [ ] Text input
    - [ ] Checkbox
    - [ ] Dropdown 
    - [ ] Tooltips

**Pre-Requisite:**

- Assuming the form fields and logic exist already in the Sample Page ticket (#186)

**Expected Outcome(s):**

- [x] Have a clinician invite page where the user can fill out the form
- [x] Data should be validated on the form
- [ ] When user clicks submit, it will log results in the browser console output

**Comment by b-f-chan** [comment]
To close this one, need to merge #152, fixing the 1024 issue

**Comment by b-f-chan** [comment]
@samrichca can this be closed?
