### ISSUE TITLE
API Hookup: Consent Wizard Progress Tracker

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#517]
Hookup the API for the consent wizard progress tracker

**Comment by samrichca** [comment]
- [ ] add a suspense boundary around <ProgressHeader />
- [ ] add a GET API request to services/api
- [ ] get the user's progress from the API in ProgressHeader/index.tsx
- [ ] move progressHeaderSteps into ProgressHeader
  - [ ] use the CONSENT_CATEGORIES enum instead of Object.keys(progress)
