### ISSUE TITLE
Bug: Optional Drop-Downs Must Allow Deselection of Entries

### ISSUE THREAD

**Issue by b-f-chan** [OHCRN/platform#842]
There is a bug where, if a user has selected a choice in an **OPTIONAL** drop-down field, but change their mind later and want to remove it (change it back to blank or empty), they **CANNOT**.

Since there are optional fields, there must be a way for users to de-select their choice.

**NOTE:** There may be multiple ways to achieve this user experience.  Please research a few viable alternatives and review them with Patrick to see which one is the best balance of user experience vs. cost/effort.  If the solution is ideal in UX but is very costly time/effort-wise, we may need to take a trade-off approach.

**Tasks:**

- [ ] Research a few UX alternatives to de-selecting the choice (e.g. click the same option again, or explicitly click a "None" or empty option)
- [ ] Review alternatives with Patrick and arrive at consensus
- [ ] Implement the chosen approach
